variables:
   DEV_USERNAME: deployment

image: node:11

cache:
    paths:
    - node_modules/

stages:
   - build
   - deploy

### BUILDS


buildDev:
  stage: build
  only:
    - dev
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
  # - LAST_TAG=$(git describe --tags)
  - npm install
  - npm run lint
  - npm run buildDev
  artifacts:
    paths:
    - ./dist


    
buildQA:
  stage: build
  only:
    - qa
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
  # - LAST_TAG=$(git describe --tags)
  - npm install
  - npm run lint
  - npm run buildDev
  artifacts:
    paths:
    - ./dist

    
### DEPLOYMENTS



deployDev:
  stage: deploy
  only:
    - dev
  environment:
    name: dev
    url: https://dev.t3.cassproject.org
  script:
   - apt-get update -y
   - apt-get install openssh-client -y
   - 'which ssh-agent || apt-get install openssh-client -y'

   - eval $(ssh-agent -s)

   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - echo "$T3_DEV_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   - chmod 600 "$T3_DEV_PRIVATE_KEY"
   - ssh-add "$T3_DEV_PRIVATE_KEY" > /dev/null

   ## Build commands
   - ssh -p22 $DEV_USERNAME@$T3_DEV_SERVER_IP "rm -rf /var/www/dev.t3.cassproject.org/*"
   - scp -P22 -r dist/* $DEV_USERNAME@$T3_DEV_SERVER_IP:/var/www/dev.t3.cassproject.org/


   
deployQA:
  stage: deploy
  only:
    - qa
  environment:
    name: qa
    url: https://qa.t3.cassproject.org
  script:
   - apt-get update -y
   - apt-get install openssh-client -y
   - 'which ssh-agent || apt-get install openssh-client -y'

   - eval $(ssh-agent -s)

   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - echo "$T3_DEV_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   - chmod 600 "$T3_DEV_PRIVATE_KEY"
   - ssh-add "$T3_DEV_PRIVATE_KEY" > /dev/null

   ## Build commands
   - ssh -p22 $DEV_USERNAME@$T3_DEV_SERVER_IP "rm -rf /var/www/qa.t3.cassproject.org/*"
   - scp -P22 -r dist/* $DEV_USERNAME@$T3_DEV_SERVER_IP:/var/www/qa.t3.cassproject.org/
   
